#cloud-config
hostname: artofwifi-template
ssh_pwauth: true

password: password
chpasswd:
  expire: False

package_update: true
package_upgrade: true

packages:
  - apache2
  - mysql-server
  - php
  - php-curl
  - nodejs 
  - npm
  # dependencies for puppeteer
  - ca-certificates 
  - fonts-liberation 
  - libnss3 
  - lsb-release 
  - wget 
  - xdg-utils

# runcmd: 
#   # enable a2enmod 
#   - a2enmod rewrite 
#   # install puppeteer
#   - npm install puppeteer


